Api usage plan
JasonLengProjects/city-feed-aws-cdk pull request #2
Opened 2022-10-25 21:04 UTC by JasonLengProjects

Added usage plan and key for the API. Adjusted request format to the newest version.
Please review.

2022-10-25 21:58 UTC, Yiwen-M requested changes
Can you change the path to /getFeedList, thanks!

2022-10-25 22:02 UTC, Yiwen-M requested changes
I'm not sure if you gonna put all the handler functions together in this hanlder.js file later (eg: put req handler), if not, maybe it's better to rename it to something like getFeedListHandler.js

2022-10-26 04:29 UTC, JasonLengProjects commented
> I'm not sure if you gonna put all the handler functions together in this hanlder.js file later (eg: put req handler), if not, maybe it's better to rename it to something like getFeedListHandler.js

Function name and source have been changed.

2022-10-26 04:33 UTC, Yiwen-M approved these changes

2022-10-26 04:33 UTC, merged